spring:
  application:
    name: API Controle Financeiro

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${USERNAME_POSTGRESQL}
    password: ${PASSWORD_POSTGRESQL}
    driver-class-name: org.postgresql.Driver
